global:
  resolve_timeout: 5m
  # SMTP configuration (uncomment and configure for email alerts)
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_from: 'alertmanager@example.com'
  # smtp_auth_username: 'your-email@gmail.com'
  # smtp_auth_password: 'your-app-password'
  # smtp_require_tls: true

# Templates for notifications
templates:
  - '/etc/alertmanager/*.tmpl'

# The root route
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true

    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      continue: true

# Alert receivers
receivers:
  # Default receiver (logs only)
  - name: 'default'
    # webhook_configs:
    #   - url: 'http://localhost:5001/'

  # Critical alerts receiver
  - name: 'critical-alerts'
    # Email notifications
    # email_configs:
    #   - to: 'oncall@example.com'
    #     headers:
    #       Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'

    # Slack notifications
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#alerts-critical'
    #     title: '🚨 {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

    # Telegram notifications
    # telegram_configs:
    #   - bot_token: 'YOUR_BOT_TOKEN'
    #     chat_id: YOUR_CHAT_ID
    #     parse_mode: 'HTML'
    #     message: '🚨 <b>CRITICAL</b>\n{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

    # Discord notifications
    # discord_configs:
    #   - webhook_url: 'https://discord.com/api/webhooks/YOUR/WEBHOOK'
    #     title: '🚨 CRITICAL ALERT'

    # PagerDuty notifications
    # pagerduty_configs:
    #   - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'

  # Warning alerts receiver
  - name: 'warning-alerts'
    # Email notifications
    # email_configs:
    #   - to: 'team@example.com'
    #     headers:
    #       Subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'

    # Slack notifications
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#alerts-warning'
    #     title: '⚠️ {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

# Inhibition rules (prevent duplicate notifications)
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
